name: '領りょう域いき展てん開かい | Ryōiki Tenkai'
on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: image_name
  REGISTRY_NAME: registry_name

jobs:
  publish-to-registry:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Qemu
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ./Dockerfile
          cache-from: type=registry,ref=${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
          tags: |
            ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: publish-to-registry

    steps:
      - name: SSH & deploy
        uses: appleboy/ssh-action@v1.2.0
        env:
          DOCKER_REGISTRY: 'docker.io'
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script_stop: true
          envs: DOCKER_REGISTRY,DOCKER_USERNAME,DOCKER_PASSWORD
          script: |
            cd ${{ vars.DEPLOYMENT_FOLDER_PATH }}
            bash ./deploy.sh
