name: Ryoiki Tenkai
on:
  push:
    branches:
      - dev
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

# Prevent multiple deployments running at once
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  IMAGE_NAME: myservice
  REGISTRY_NAME: repo

jobs:
  publish-to-registry:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.ref_name == 'master' || github.ref_name == 'dev'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ./CI/Dockerfile
          cache-from: type=registry,ref=${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
          tags: ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  trigger-coolify:
    needs: publish-to-registry
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.ref_name == 'master' || github.ref_name == 'dev'

    steps:
      - name: Update IMAGE_SHA environment
        env:
          API_URL: "https://myservice.coolify.com/api/v1/services/${{ github.ref_name == 'master' && secrets.COOLIFY_SERVICE_UUID || secrets.COOLIFY_SERVICE_UUID_DEV }}/envs"
        run: |
          curl -X PATCH \
          -H "Authorization: Bearer ${{ secrets.COOLIFY_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{
            "key": "IMAGE_SHA",
            "value": "${{ github.sha }}",
            "is_preview": false,
            "is_build_time": true,
            "is_literal": true,
            "is_multiline": false,
            "is_shown_once": false
          }' $API_URL

      - name: Trigger deployment
        env:
          API_URL: "https://myservice.coolify.com/api/v1/deploy?uuid=${{ github.ref_name == 'master' && secrets.COOLIFY_SERVICE_UUID || secrets.COOLIFY_SERVICE_UUID_DEV }}"
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.COOLIFY_API_KEY }}" \
          -H "Content-Type: application/json" \
           $API_URL
