name: "Pull - Build - Deploy"
on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: your-image-name
  REGISTRY_NAME: docker-registry-name
  IMAGE_TAG: yout-image-tag
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  SERVER_HOST: ${{ secrets.SSH_HOST }}
  SERVER_USERNAME: ${{ secrets.SSH_USERNAME }}
  SERVER_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  DEPLOYMENT_DIR: ${{ vars.DEPLOYMENT_DIR }}

jobs:
  publish-to-registry:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ env.REGISTRY_NAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs: publish-to-registry

    steps:
      - name: SSH & deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USERNAME }}
          key: ${{ env.SERVER_PRIVATE_KEY }}
          script: |
            ssh-keyscan -H ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts
            cd ${{ env.DEPLOYMENT_DIR }}
            docker login -u ${{ env.REGISTRY_NAME }} -p ${{ env.DOCKERHUB_TOKEN }}
            docker pull ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            bash ./deploy.sh
            docker logout
